name: Survey Backup
on:
  push:
    branches:
      - backup-neo4j-on-s3
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@master
      - name: Download file via SSH
        uses: nicklasfrahm/scp-action@main
        with:
          direction: download
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PROD_KEY }}
          insecure_ignore_fingerprint: true
          source: "/home/ubuntu/survey_db_backup/neo4j-20220210.dump"
          target: "survey_db_backup.dump"

      - name: list files again
        run: |
          pwd
          mkdir backup
          ls
          mv survey_db_backup.dump backup
          cd backup
          pwd
          ls -l *   
      - name: Connect s3 bucket
        uses: jakejarvis/s3-sync-action@master
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-2'   # optional: defaults to us-east-1
          SOURCE_DIR: '/home/runner/work/qxf2-survey/qxf2-survey/backup'
        
