name: Survey Backup
on:
  push:
    branches:
      - backup-neo4j-on-s3
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@master
      - name: Download file via SSH
        uses: nicklasfrahm/scp-action@main
        with:
          direction: download
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PROD_KEY }}
          source: "/home/ubuntu/survey_db_backup/neo4j-20220210.dump"
          target: "survey_db_backup.dump"
      - name: list files
        run: |
          ls -al