name: Survey Backup
on:
  push:
    branches:
      - backup-neo4j-on-s3
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: copy file via ssh key
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PROD_KEY }}
        script:  |
          pwd
        source: "/home/ubuntu/survey_db_backup/neo4j-20220210.dump"
        target: "survey_db.dump"
    - name: list files
      run: |
        ls -al
        
